# Generated by Django 4.2.7 on 2023-11-11 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('date_received', models.DateField()),
                ('error_level', models.CharField(max_length=20)),
                ('functionality_category', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Programmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ErrorCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correction_code', models.CharField(max_length=50)),
                ('error_code', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('correction_period', models.IntegerField()),
                ('cost_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('programmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='software_company_app.programmer')),
            ],
        ),
    ]
